### ISSUE TITLE
Only shows full pages of items, missing off remaining items

### ISSUE THREAD

**Issue by MattKevan** [sabbir-rupom/pagination-jquery#1]
I'm having a problem where if the number of items don't meet the number set for items per page then they're hidden.

For example if I have 21 items and it's set to display 9 items per page, then the pager only goes to two, and the last three items are hidden. Is there a way of getting it to display all items, even if there's not a full count of objects?

**Comment by sabbir-rupom** [comment]
Hi Matt! 

Many thanks for raising this issue. Somehow I had overlooked the bug during my last update. I have fixed the issue now. 

Please check the new version 2.1 and update this library in your project assets.
https://github.com/sabbir-rupom/pagination-jquery/releases/tag/v2.1

I hope that all the bugs been sorted out and wish that this little plugin will be useful in your project. 

If you find any more bugs, please raise in this project's issue list.

**Comment by MattKevan** [comment]
Thanks for your help - it works perfectly now. Much appreciated!
